// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpooiunzmnwywnqnfisy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwb29pdW56bW53eXducW5maXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODM5NjIsImV4cCI6MjA2OTA1OTk2Mn0.KJhxDogoiDWZpa4Zas5xOhLZNFNFf3ucrg_TQJ-_kxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});